# Generated by Django 4.2.6 on 2023-11-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists. '}, max_length=254, unique=True),
        ),
    ]
