# Generated by Django 4.2.6 on 2023-12-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_appuser_is_verified_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
