# Generated by Django 4.2.6 on 2023-12-18 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_confirmationcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='type',
            field=models.CharField(choices=[('AccountVerification', 'AccountVerification'), ('ForgottenPassword', 'ForgottenPassword')], max_length=20),
            preserve_default=False,
        ),
    ]
