# Generated by Django 4.2.6 on 2023-12-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_confirmationcode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='type',
            field=models.CharField(choices=[('AccountVerification', 'Account Verification'), ('ForgottenPassword', 'Forgotten Password')], max_length=21),
        ),
    ]
