# Generated by Django 4.2.6 on 2024-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_confirmationcode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists. '}, max_length=30, unique=True),
        ),
    ]
