# Generated by Django 4.2.6 on 2024-02-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measures',
            name='goal',
            field=models.CharField(blank=True, choices=[('Bulk', 'Bulk'), ('Cut', 'Cut'), ('Maintain', 'Maintain')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='measures',
            name='activity',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Light', 'Light'), ('Moderate', 'Moderate'), ('Very', 'Very'), ('Extreme', 'Extreme')], max_length=10, null=True),
        ),
    ]
