# Generated by Django 4.2.6 on 2024-02-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_birthday'),
        ('health', '0002_measures_goal_alter_measures_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measures',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='measures',
            name='goal',
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Light', 'Light'), ('Moderate', 'Moderate'), ('Very', 'Very'), ('Extreme', 'Extreme')], max_length=10, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Bulk', 'Bulk'), ('Cut', 'Cut'), ('Maintain', 'Maintain')], max_length=9, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
