# Generated by Django 4.2.6 on 2024-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_measures_activity_remove_measures_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='goal',
            field=models.CharField(blank=True, choices=[('Bulk', 'Bulk'), ('Cut', 'Cut'), ('Maintain', 'Maintain')], max_length=10, null=True),
        ),
    ]
