# Generated by Django 4.2.6 on 2024-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_fitness_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='goal',
            field=models.CharField(blank=True, choices=[('Bulk', 'Bulk'), ('Cut', 'Cut'), ('Maintain', 'Maintain')], max_length=50, null=True),
        ),
    ]
