# Generated by Django 4.2.6 on 2024-04-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_picture'),
        ('health', '0007_alter_historicalmeasures_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='measures',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
