# Generated by Django 4.2.6 on 2025-01-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='exercises',
            field=models.ManyToManyField(related_name='template_exercises', to='workouts.workouttemplateexerciseitem'),
        ),
    ]
