# Generated by Django 4.2.6 on 2023-11-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('workouts', '0002_alter_exercise_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
