# Generated by Django 4.2.6 on 2025-02-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workouttemplate_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='workout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttemplate'),
        ),
    ]
