# Generated by Django 4.2.6 on 2025-02-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_full_name_alter_profile_gender'),
        ('workouts', '0003_workoutsession_workout_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='workout_template',
        ),
        migrations.CreateModel(
            name='TemplateWorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttemplate')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutsession')),
            ],
        ),
    ]
