# Generated by Django 4.2.6 on 2025-02-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workoutsession_workout_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateworkoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
