# Generated by Django 4.2.6 on 2024-01-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_is_published_set_bodyweight_set_to_failure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
