# Generated by Django 4.2.6 on 2025-02-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_templateworkoutsession_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.routine')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='workouts',
            field=models.ManyToManyField(related_name='routine', through='workouts.RoutineWorkout', to='workouts.workouttemplate'),
        ),
    ]
