# Generated by Django 4.2.6 on 2024-02-10 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_set_options_historicalset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalset',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
