# Generated by Django 4.2.6 on 2024-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_historicalset_updated_at_set_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='targeted_muscle_groups',
            field=models.ManyToManyField(to='workouts.musclegroup'),
        ),
    ]
