# Generated by Django 4.2.6 on 2024-03-24 21:19

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_musclegroup_exercise_targeted_muscle_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
