# Generated by Django 4.2.6 on 2024-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_exercise_video_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
