# Generated by Django 4.2.6 on 2024-06-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_rename_information_exercise_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='targeted_muscle_groups',
            field=models.ManyToManyField(blank=True, null=True, to='workouts.musclegroup'),
        ),
    ]
