# Generated by Django 4.2.6 on 2024-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_exercise_is_cardio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='is_cardio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
