# Generated by Django 4.2.6 on 2024-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_exercise_bodyweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='bodyweight',
            field=models.BooleanField(default=False),
        ),
    ]
