# Generated by Django 4.2.6 on 2024-06-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_full_name_alter_profile_gender'),
        ('workouts', '0021_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupersetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('exercises', models.ManyToManyField(to='workouts.exercisesession')),
            ],
        ),
    ]
