# Generated by Django 4.2.6 on 2024-06-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workouts', '0022_supersetsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
