# Generated by Django 4.2.6 on 2024-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_remove_workoutsession_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
