# Generated by Django 4.2.6 on 2024-06-28 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_full_name_alter_profile_gender'),
        ('workouts', '0026_supersetsession_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercisesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercisesession',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercisesession',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
