# Generated by Django 4.2.6 on 2024-06-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0027_workoutexercisesession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercisesession',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
