# Generated by Django 4.2.6 on 2024-06-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0028_workoutexercisesession_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercisesession',
            name='order',
        ),
        migrations.AlterField(
            model_name='exercisesessionitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
