# Generated by Django 4.2.6 on 2024-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_remove_workoutexercisesession_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercisesession',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='workoutexercisesession',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
