# Generated by Django 4.2.6 on 2024-07-06 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0031_remove_workoutexercisesession_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='new_time',
            field=models.TimeField(default=datetime.time(0, 20)),
            preserve_default=False,
        ),
    ]
