# Generated by Django 4.2.6 on 2024-07-06 14:00
import datetime

from django.db import migrations, models


def convert_time(apps, schema_editor):
    YourModel = apps.get_model('workouts', 'Interval')
    for obj in YourModel.objects.all():
        # Assuming the integer field represents seconds since midnight
        seconds = obj.time
        obj.new_time = (datetime.time(0, 20, 0))
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('workouts', '0032_interval_new_time'),
    ]

    operations = [
        migrations.RunPython(convert_time)
    ]
