# Generated by Django 4.2.6 on 2024-07-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0033_convert_time_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='time',
        ),
    ]
