# Generated by Django 4.2.6 on 2024-07-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0034_remove_interval_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='new_time',
        ),
    ]
