# Generated by Django 4.2.6 on 2024-07-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0035_rename_new_time_interval_time'),
    ]

    operations = [
    ]
