# Generated by Django 4.2.6 on 2024-08-03 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0036_remove_interval_new_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
