# Generated by Django 4.2.6 on 2024-09-01 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_full_name_alter_profile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0037_interval_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='tips_and_tricks',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_tutorial',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalExerciseInstruction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.profile')),
                ('exercise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workouts.exercise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical exercise instruction',
                'verbose_name_plural': 'historical exercise instructions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExerciseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='workouts.exercise')),
            ],
        ),
    ]
