# Generated by Django 4.2.6 on 2024-09-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workouts', '0039_historicalcustomexercise_customexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstruction',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='historicalexerciseinstruction',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exerciseinstruction',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseinstruction',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalexerciseinstruction',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalexerciseinstruction',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
